# Generated by Django 2.2.3 on 2020-04-11 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 0, 18, 48, 465512), verbose_name='Date added'),
        ),
    ]
